// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47sQBl0e9zx612oKluXqZzFd7d_RL_ig',
    appId: '1:466968902146:web:83293b11c407969cde051b',
    messagingSenderId: '466968902146',
    projectId: 'flutter-project-abd93',
    authDomain: 'flutter-project-abd93.firebaseapp.com',
    storageBucket: 'flutter-project-abd93.appspot.com',
    measurementId: 'G-4NEFNFY236',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWYizecrEZiWNmw0y0IBMdPfYfnnYuvE',
    appId: '1:466968902146:android:b06b442dab637d57de051b',
    messagingSenderId: '466968902146',
    projectId: 'flutter-project-abd93',
    storageBucket: 'flutter-project-abd93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZTK_low_gkOjI5w4lK9wkm4fDVneSSA',
    appId: '1:466968902146:ios:c68aef62f9800603de051b',
    messagingSenderId: '466968902146',
    projectId: 'flutter-project-abd93',
    storageBucket: 'flutter-project-abd93.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZTK_low_gkOjI5w4lK9wkm4fDVneSSA',
    appId: '1:466968902146:ios:c68aef62f9800603de051b',
    messagingSenderId: '466968902146',
    projectId: 'flutter-project-abd93',
    storageBucket: 'flutter-project-abd93.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47sQBl0e9zx612oKluXqZzFd7d_RL_ig',
    appId: '1:466968902146:web:3f5313f7363f5ec8de051b',
    messagingSenderId: '466968902146',
    projectId: 'flutter-project-abd93',
    authDomain: 'flutter-project-abd93.firebaseapp.com',
    storageBucket: 'flutter-project-abd93.appspot.com',
    measurementId: 'G-46W5NXHHW8',
  );
}
